os: linux
dist: trusty
language: python
services: docker

env:
  global:
  - SMARTGIT_VER=17.0.4

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --build-arg SMARTGIT_VER=$SMARTGIT_VER
                  --tag x11vnc/smartgit-desktop:latest
                  --tag x11vnc/smartgit-desktop:$SMARTGIT_VER . &&
     docker push x11vnc/smartgit-desktop &&
     touch success'
  # Test script without launching webbrowser and push new image if successful
  - './smartgit_desktop.py -d -n -v test_project && docker stop $(docker ps -q)'
  - './smartgit_desktop.py -d -n && docker stop $(docker ps -q)'
  - docker images
